/** @noSelfInFile */
import Card from "Cards/Card";
import Board from "Screens/Board";
import { CharacterTypes } from "./Enums";
import GameManager from "./GameManager";
import Point from "./Point";
export default class Dealer {
    gameManager: GameManager;
    lootCards: Card[];
    board: Board;
    constructor(gameManager: GameManager, board: Board);
    setup(): void;
    dealEdel(): void;
    dealHandAtStartOfFight(): void;
    dealAtStartOfFightForCharacter(character: CharacterTypes): void;
    finishPlayerDeal(): void;
    getCharacterHand(characterType: CharacterTypes): Card[];
    putCharacterHandBackInDeck(characterType: CharacterTypes): void;
    static initializePlayerDeck(gameManager: GameManager): void;
    static shuffle(gameManager: GameManager, characterType: string): void;
    dealCards(characterType: CharacterTypes, removedIndices?: number[]): void;
    redrawDeck(characterType: CharacterTypes): void;
    discardCards(characterType: CharacterTypes, cards: Card[]): number[];
    discardForCharacter(characterType: CharacterTypes): number[];
    dealNextHand(): void;
    getDeckPosition(characterType: CharacterTypes): Point;
    getCardPointInHand(characterType: CharacterTypes, cardIndex: number, totalCardCount: number): Point;
    startDealAnimation(characterType: CharacterTypes, card: Card, targetX: number, targetY: number): void;
    getDealFinishMethod(characterType: CharacterTypes): (() => void) | undefined;
    finishDeal(characterType: CharacterTypes): void;
    startDiscardAnimation(characterType: CharacterTypes, cards: Card[]): void;
    private getDiscardPosition;
    startReturnToDeckAnimation(characterType: CharacterTypes, cards: Card[], onFinish?: () => void): void;
    finishUpAnimation(card: Card, onFinish?: () => void): void;
    initializeEnemyDeck(): void;
    determineEdelSuit(): void;
    getLootCards(): Card[];
    addLootCard(card: Card): void;
    hasLootCard(card: Card): boolean;
    deselectLootCards(): void;
    addLootCardsToPlayer(): void;
}
