/** @noSelfInFile */
import { Suits, Ranks, CharacterTypes, EdelRanks } from "./Enums";
import Card from "Cards/Card";
import GameManager from "./GameManager";
import Point from "./Point";
export default class Dealer {
    gameManager: GameManager;
    lootCards: Card[];
    constructor(gameManager: GameManager);
    setup(): void;
    dealEdel(): void;
    dealHand(): void;
    putHandBackInDeck(characterType: CharacterTypes): void;
    getCharacterHand(characterType: CharacterTypes): Card[];
    putCharacterHandBackInDeck(characterType: CharacterTypes): void;
    static initializePlayerDeck(gameManager: GameManager): void;
    static shuffle(gameManager: GameManager, characterType: string): void;
    static getNewCard(gameManager: GameManager, rank: Ranks | EdelRanks, suit: Suits): Card;
    static getRandomCard(gameManager: GameManager): Card;
    dealCards(characterType: CharacterTypes): void;
    redrawDeck(characterType: CharacterTypes): void;
    discardCards(characterType: CharacterTypes, cards: Card[]): void;
    dealNextRound(): void;
    getDeckPosition(characterType: CharacterTypes): Point;
    getFinalCardPosition(characterType: CharacterTypes, cardIndex: number, totalCardCount: number): Point;
    startDealAnimation(card: Card, targetX: number, targetY: number): void;
    startDiscardAnimation(characterType: CharacterTypes, cards: Card[]): void;
    private getDiscardPosition;
    startReturnToDeckAnimation(characterType: CharacterTypes, cards: Card[]): void;
    finishUpAnimation(card: Card): void;
    initializeEnemyDeck(): void;
    determineEdelSuit(): void;
    convertToEdelSuit(card: Card): Card;
    convertToEdelSuitForCharacter(characterType: string): void;
    convertBackToOriginalSuit(card: Card): Card;
    convertBackToOriginalSuitForCharacter(characterType: string): void;
    getLootCards(): Card[];
    addLootCard(card: Card): void;
    hasLootCard(card: Card): boolean;
    deselectLootCards(): void;
    addLootCardsToPlayer(): void;
}
