--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
____exports.GameStates = GameStates or ({})
____exports.GameStates.MAIN_MENU = "MAIN_MENU"
____exports.GameStates.NEW_GAME_MENU = "NEW_GAME_MENU"
____exports.GameStates.BOARD = "BOARD"
____exports.GameStates.PAUSE_MENU = "PAUSE_MENU"
____exports.GameStates.WIN_SCREEN = "WIN_SCREEN"
____exports.GameStates.LOSE_SCREEN = "LOSE_SCREEN"
____exports.GameStates.MAP = "MAP"
____exports.GameStates.SHOP = "SHOP"
____exports.GameStates.LEVEL_UP = "LEVEL_UP"
____exports.GameStates.PERKS = "PERKS"
____exports.Suits = Suits or ({})
____exports.Suits.HEARTS = "HEARTS"
____exports.Suits.BELLS = "BELLS"
____exports.Suits.ACORNS = "ACORNS"
____exports.Suits.LEAVES = "LEAVES"
____exports.Ranks = Ranks or ({})
____exports.Ranks.KING = "KING"
____exports.Ranks.OVERLORD = "OVERLORD"
____exports.Ranks.SERGEANT = "SERGEANT"
____exports.Ranks.BANNER = "BANNER"
____exports.Ranks.THIEF = "THIEF"
____exports.Ranks.PRIEST = "PRIEST"
____exports.Ranks.SOLDIER = "SOLDIER"
____exports.Ranks.BARON = "BARON"
____exports.Ranks.JESTER = "JESTER"
____exports.Ranks.DEUCE = "DEUCE"
____exports.TrumpRanks = TrumpRanks or ({})
____exports.TrumpRanks.CHOSEN = "CHOSEN"
____exports.TrumpRanks.DEVIL = "DEVIL"
____exports.TrumpRanks.POPE = "POPE"
____exports.TrumpRanks.EMPEROR = "EMPEROR"
____exports.TrumpRanks.BARD = "BARD"
____exports.TrumpRanks.DUKE = "DUKE"
____exports.TrumpRanks.KNIGHT = "KNIGHT"
____exports.CharacterTypes = CharacterTypes or ({})
____exports.CharacterTypes.PLAYER = "PLAYER"
____exports.CharacterTypes.ENEMY = "ENEMY"
____exports.MapNodeTypes = MapNodeTypes or ({})
____exports.MapNodeTypes.BATTLE = "BATTLE"
____exports.MapNodeTypes.SHOP = "SHOP"
____exports.EnemyTypes = EnemyTypes or ({})
____exports.EnemyTypes.KOBOLD = "KOBOLD"
____exports.EnemyTypes.NIXIE = "NIXIE"
____exports.EnemyTypes.OGRE = "OGRE"
____exports.EnemyTypes.TATZELWURM = "TATZELWURM"
____exports.Perks = Perks or ({})
____exports.Perks.EXTRA_CARD = "EXTRA_CARD"
____exports.Perks.EXTRA_DISCARD = "EXTRA_DISCARD"
____exports.Perks.INCREASED_LOOT = "INCREASED_LOOT"
____exports.AssetIds = AssetIds or ({})
____exports.AssetIds.BASE_CARD_TEMPLATE = "BASE_CARD_TEMPLATE"
____exports.AssetIds.SUIT = "SUIT"
____exports.AssetIds.LETS_FIGHT_BUTTON = "LETS_FIGHT_BUTTON"
____exports.AssetIds.RANK = "RANK"
____exports.AssetIds.ATTACK_BUTTON = "ATTACK_BUTTON"
____exports.AssetIds.DISCARD_BUTTON = "DISCARD_BUTTON"
____exports.AssetIds.DESELECT_BUTTON = "DESELECT_BUTTON"
____exports.FontIds = FontIds or ({})
____exports.FontIds.ATTACK_BUTTON_CAPTION = "ATTACK_BUTTON_CAPTION"
____exports.FontIds.DISCARD_BUTTON_CAPTION = "DISCARD_BUTTON_CAPTION"
____exports.FontIds.DESELECT_BUTTON_CAPTION = "DESELECT_BUTTON_CAPTION"
____exports.AnimationIds = AnimationIds or ({})
____exports.AnimationIds.CARD_BASE_SELECT = "CARD_BASE_SELECT"
____exports.AnimationIds.CARD_BASE_UNSELECT = "CARD_BASE_UNSELECT"
____exports.AnimationIds.CARD_SUIT_NORMAL_SELECT = "CARD_SUIT_NORMAL_SELECT"
____exports.AnimationIds.CARD_SUIT_NORMAL_UNSELECT = "CARD_SUIT_NORMAL_UNSELECT"
____exports.AnimationIds.CARD_SUIT_FLIPPED_SELECT = "CARD_SUIT_FLIPPED_SELECT"
____exports.AnimationIds.CARD_SUIT_FLIPPED_UNSELECT = "CARD_SUIT_FLIPPED_UNSELECT"
____exports.AnimationIds.CARD_RANK_SELECT = "CARD_RANK_NORMAL_SELECT"
____exports.AnimationIds.CARD_RANK_UNSELECT = "CARD_RANK_NORMAL_UNSELECT"
return ____exports
