export declare enum GameStates {
    MAIN_MENU = "MAIN_MENU",
    NEW_GAME_MENU = "NEW_GAME_MENU",
    BOARD = "BOARD",
    PAUSE_MENU = "PAUSE_MENU",
    WIN_SCREEN = "WIN_SCREEN",
    LOSE_SCREEN = "LOSE_SCREEN",
    MAP = "MAP",
    SHOP = "SHOP",
    LEVEL_UP = "LEVEL_UP",
    PERKS = "PERKS"
}
export declare enum Suits {
    HEARTS = "HEARTS",
    BELLS = "BELLS",
    ACORNS = "ACORNS",
    LEAVES = "LEAVES"
}
export declare enum Ranks {
    KING = "KING",
    OVERLORD = "OVERLORD",
    SERGEANT = "SERGEANT",
    BANNER = "BANNER",
    THIEF = "THIEF",
    PRIEST = "PRIEST",
    SOLDIER = "SOLDIER",
    BARON = "BARON",
    JESTER = "JESTER",
    DEUCE = "DEUCE"
}
export declare enum TrumpRanks {
    CHOSEN = "CHOSEN",
    DEVIL = "DEVIL",
    POPE = "POPE",
    EMPEROR = "EMPEROR",
    BARD = "BARD",
    DUKE = "DUKE",
    KNIGHT = "KNIGHT"
}
export declare enum CharacterTypes {
    PLAYER = "PLAYER",
    ENEMY = "ENEMY"
}
export declare enum MapNodeTypes {
    BATTLE = "BATTLE",
    SHOP = "SHOP"
}
export declare enum EnemyTypes {
    KOBOLD = "KOBOLD",
    NIXIE = "NIXIE",
    OGRE = "OGRE",
    TATZELWURM = "TATZELWURM"
}
export declare enum Perks {
    EXTRA_CARD = "EXTRA_CARD",
    EXTRA_DISCARD = "EXTRA_DISCARD",
    INCREASED_LOOT = "INCREASED_LOOT"
}
export declare enum AssetIds {
    BASE_CARD_TEMPLATE = "BASE_CARD_TEMPLATE",
    SUIT = "SUIT",
    LETS_FIGHT_BUTTON = "LETS_FIGHT_BUTTON",
    RANK = "RANK",
    ATTACK_BUTTON = "ATTACK_BUTTON",
    DISCARD_BUTTON = "DISCARD_BUTTON",
    DESELECT_BUTTON = "DESELECT_BUTTON"
}
export declare enum FontIds {
    ATTACK_BUTTON_CAPTION = "ATTACK_BUTTON_CAPTION",
    DISCARD_BUTTON_CAPTION = "DISCARD_BUTTON_CAPTION",
    DESELECT_BUTTON_CAPTION = "DESELECT_BUTTON_CAPTION"
}
export declare enum AnimationIds {
    CARD_BASE_SELECT = "CARD_BASE_SELECT",
    CARD_BASE_UNSELECT = "CARD_BASE_UNSELECT",
    CARD_SUIT_NORMAL_SELECT = "CARD_SUIT_NORMAL_SELECT",
    CARD_SUIT_NORMAL_UNSELECT = "CARD_SUIT_NORMAL_UNSELECT",
    CARD_SUIT_FLIPPED_SELECT = "CARD_SUIT_FLIPPED_SELECT",
    CARD_SUIT_FLIPPED_UNSELECT = "CARD_SUIT_FLIPPED_UNSELECT",
    CARD_RANK_SELECT = "CARD_RANK_NORMAL_SELECT",
    CARD_RANK_UNSELECT = "CARD_RANK_NORMAL_UNSELECT"
}
