export declare enum GameStates {
    MAIN_MENU = "MAIN_MENU",
    NEW_GAME_MENU = "NEW_GAME_MENU",
    BOARD = "BOARD",
    PAUSE_MENU = "PAUSE_MENU",
    WIN_SCREEN = "WIN_SCREEN",
    LOSE_SCREEN = "LOSE_SCREEN",
    MAP = "MAP",
    SHOP = "SHOP",
    LEVEL_UP = "LEVEL_UP",
    PERKS = "PERKS"
}
export declare enum Suits {
    HEARTS = "HEARTS",
    BELLS = "BELLS",
    ACORNS = "ACORNS",
    LEAVES = "LEAVES"
}
export declare enum Ranks {
    KING = "KING",
    OVERLORD = "OVERLORD",
    SERGEANT = "SERGEANT",
    BANNER = "BANNER",
    THIEF = "THIEF",
    PRIEST = "PRIEST",
    SOLDIER = "SOLDIER",
    BARON = "BARON",
    JESTER = "JESTER",
    DEUCE = "DEUCE"
}
export declare enum EdelRanks {
    CHOSEN = "CHOSEN",
    DEVIL = "DEVIL",
    POPE = "POPE",
    EMPEROR = "EMPEROR",
    BARD = "BARD",
    DUKE = "DUKE",
    KNIGHT = "KNIGHT"
}
export declare enum CharacterTypes {
    PLAYER = "PLAYER",
    ENEMY = "ENEMY"
}
export declare enum MapNodeTypes {
    BATTLE = "BATTLE",
    SHOP = "SHOP"
}
export declare enum EnemyTypes {
    KOBOLD = "KOBOLD",
    NIXIE = "NIXIE",
    OGRE = "OGRE",
    TATZELWURM = "TATZELWURM"
}
export declare enum Perks {
    EXTRA_CARD = "EXTRA_CARD",
    EXTRA_DISCARD = "EXTRA_DISCARD",
    INCREASED_LOOT = "INCREASED_LOOT"
}
export declare enum AssetIds {
    BASE_CARD_TEMPLATE = "BASE_CARD_TEMPLATE",
    SUIT = "SUIT",
    LETS_FIGHT_BUTTON = "LETS_FIGHT_BUTTON",
    RANK = "RANK",
    ATTACK_BUTTON = "ATTACK_BUTTON",
    DISCARD_BUTTON = "DISCARD_BUTTON",
    DESELECT_BUTTON = "DESELECT_BUTTON",
    POINT_DISPLAY = "POINT_DISPLAY",
    PLAYER_PORTRAIT_BACKGROUND = "PLAYER_PORTRAIT_BACKGROUND",
    ENEMY_PORTRAIT_BACKGROUND = "ENEMY_PORTRAIT_BACKGROUND",
    PLAYER_PORTRAIT = "PLAYER_PORTRAIT",
    ENEMY_PORTRAIT = "ENEMY_PORTRAIT",
    PLAYER_DECK = "PLAYER_DECK",
    ENEMY_DECK = "ENEMY_DECK",
    GRASS_BACKGROUND = "GRASS_BACKGROUND",
    PERKS_BUTTON = "PERKS_BUTTON",
    BASIC_WIN_FIRE = "BASIC_WIN_FIRE"
}
export declare enum TextIds {
    LETS_FIGHT_BUTTON_CAPTION = "LETS_FIGHT_BUTTON_CAPTION",
    ATTACK_BUTTON_CAPTION = "ATTACK_BUTTON_CAPTION",
    DISCARD_BUTTON_CAPTION = "DISCARD_BUTTON_CAPTION",
    DISCARD_BUTTON_COUNTER = "DISCARD_BUTTON_COUNTER",
    DESELECT_BUTTON_CAPTION = "DESELECT_BUTTON_CAPTION",
    POINTS_PLAYER = "POINTS_PLAYER",
    POINTS_ENEMY = "POINTS_ENEMY",
    EDEL_SUIT_LABEL = "EDEL_SUIT_LABEL",
    PLAYER_PORTRAIT_NAME = "PLAYER_PORTRAIT_NAME",
    ENEMY_PORTRAIT_NAME = "ENEMY_PORTRAIT_NAME",
    PLAYER_PORTRAIT_LEVEL = "PLAYER_PORTRAIT_LEVEL",
    ENEMY_PORTRAIT_LEVEL = "ENEMY_PORTRAIT_LEVEL",
    PLAYER_PORTRAIT_EXPERIENCE = "PLAYER_PORTRAIT_EXPERIENCE",
    PLAYER_PORTRAIT_MONEY = "PLAYER_PORTRAIT_MONEY",
    PLAYER_PERKS = "PLAYER_PERKS",
    PLAYER_POWER = "PLAYER_POWER",
    PLAYER_VALUE = "PLAYER_VALUE",
    ENEMY_POWER = "ENEMY_POWER",
    ENEMY_VALUE = "ENEMY_VALUE",
    WIN_FIRE_TEXT = "WIN_FIRE_TEXT",
    WINNINGS = "WINNINGS"
}
export declare enum AnimationIds {
    CARD_BASE_SELECT = "CARD_BASE_SELECT",
    CARD_BASE_UNSELECT = "CARD_BASE_UNSELECT",
    CARD_SUIT_NORMAL_SELECT = "CARD_SUIT_NORMAL_SELECT",
    CARD_SUIT_NORMAL_UNSELECT = "CARD_SUIT_NORMAL_UNSELECT",
    CARD_SUIT_FLIPPED_SELECT = "CARD_SUIT_FLIPPED_SELECT",
    CARD_SUIT_FLIPPED_UNSELECT = "CARD_SUIT_FLIPPED_UNSELECT",
    CARD_RANK_SELECT = "CARD_RANK_NORMAL_SELECT",
    CARD_RANK_UNSELECT = "CARD_RANK_NORMAL_UNSELECT"
}
