export enum GameStates {
    MAIN_MENU = "MAIN_MENU",
    NEW_GAME_MENU = "NEW_GAME_MENU",
    BOARD = "BOARD",
    PAUSE_MENU = "PAUSE_MENU",
    WIN_SCREEN = "WIN_SCREEN",
    LOSE_SCREEN = "LOSE_SCREEN",
    MAP = "MAP",
    SHOP = "SHOP",
    LEVEL_UP = "LEVEL_UP",
    PERKS = "PERKS",
}
export enum Suits {
    HEARTS = "HEARTS",
    BELLS = "BELLS",
    ACORNS = "ACORNS",
    LEAVES = "LEAVES",
}

export enum Ranks {
    KING = "KING",
    OVERLORD = "OVERLORD",
    SERGEANT = "SERGEANT",
    BANNER = "BANNER",
    THIEF = "THIEF",
    PRIEST = "PRIEST",
    SOLDIER = "SOLDIER",
    BARON = "BARON",
    JESTER = "JESTER",
    DEUCE = "DEUCE"
}

export enum EdelRanks {
    CHOSEN = "CHOSEN",
    DEVIL = "DEVIL",
    POPE = "POPE",
    EMPEROR = "EMPEROR",
    BARD = "BARD",
    DUKE = "DUKE",
    KNIGHT = "KNIGHT",
}

export enum CharacterTypes {
    PLAYER = "PLAYER",
    ENEMY = "ENEMY",
}

export enum MapNodeTypes {
    BATTLE = "BATTLE",
    SHOP = "SHOP",
    // Belsnickel
    // Bergmonch
    // Feldgeister
}

export enum EnemyTypes {
    KOBOLD = "KOBOLD",
    NIXIE = "NIXIE",
    OGRE = "OGRE",
    TATZELWURM = "TATZELWURM",
    // Alp
    // Lindworm
    // Night raven

}

export enum Perks {
    EXTRA_CARD = "EXTRA_CARD",
    EXTRA_DISCARD = "EXTRA_DISCARD",
    INCREASED_LOOT = "INCREASED_LOOT",
}

export enum AssetIds {
    BASE_CARD_TEMPLATE = "BASE_CARD_TEMPLATE",
    SUIT = "SUIT",
    RANK = "RANK",
    LETS_FIGHT_BUTTON = "LETS_FIGHT_BUTTON",
    ATTACK_BUTTON = "ATTACK_BUTTON",
    DISCARD_BUTTON = "DISCARD_BUTTON",
    DESELECT_BUTTON = "DESELECT_BUTTON",
    POINT_DISPLAY = "POINT_DISPLAY",
    PLAYER_PORTRAIT_BACKGROUND = "PLAYER_PORTRAIT_BACKGROUND", 
    ENEMY_PORTRAIT_BACKGROUND = "ENEMY_PORTRAIT_BACKGROUND",
    PLAYER_PORTRAIT = "PLAYER_PORTRAIT",
    ENEMY_PORTRAIT = "ENEMY_PORTRAIT",
    PLAYER_DECK = "PLAYER_DECK",
    ENEMY_DECK = "ENEMY_DECK",
    BACKGROUND = "GRASS_BACKGROUND",
    PERKS_BUTTON = "PERKS_BUTTON",
    BASIC_WIN_FIRE = "BASIC_WIN_FIRE",
    EDEL_BOARD = "EDEL_BOARD",
    EDEL_SUIT_ICON_LEFT = "EDEL_SUIT_ICON_LEFT",
    EDEL_SUIT_ICON_RIGHT = "EDEL_SUIT_ICON_RIGHT",
    TOOLTIP_BACKGROUND = "TOOLTIP_BACKGROUND",
    PLAYER_ATTACK_POWER_ICON = "PLAYER_ATTACK_POWER_ICON",
    ENEMY_ATTACK_POWER_ICON = "ENEMY_ATTACK_POWER_ICON",
    PLAYER_VALUE_ICON = "PLAYER_VALUE_ICON",
    ENEMY_VALUE_ICON = "ENEMY_VALUE_ICON",
    MONEY_ICON = "MONEY_ICON",
    TOOLTIP_POWER_ICON = "TOOLTIP_POWER_ICON",
    TOOLTIP_VALUE_ICON = "TOOLTIP_VALUE_ICON",
}

export enum TextIds {
    LETS_FIGHT_BUTTON_CAPTION = "LETS_FIGHT_BUTTON_CAPTION",
    ATTACK_BUTTON_CAPTION = "ATTACK_BUTTON_CAPTION",
    DISCARD_BUTTON_CAPTION = "DISCARD_BUTTON_CAPTION",
    DISCARD_BUTTON_COUNTER = "DISCARD_BUTTON_COUNTER",
    DESELECT_BUTTON_CAPTION = "DESELECT_BUTTON_CAPTION",
    POINTS_PLAYER = "POINTS_PLAYER",
    POINTS_ENEMY = "POINTS_ENEMY",
    EDEL_LABEL = "EDEL_LABEL",
    PLAYER_PORTRAIT_NAME = "PLAYER_PORTRAIT_NAME",
    ENEMY_PORTRAIT_NAME = "ENEMY_PORTRAIT_NAME",
    PLAYER_PORTRAIT_LEVEL = "PLAYER_PORTRAIT_LEVEL",
    ENEMY_PORTRAIT_LEVEL = "ENEMY_PORTRAIT_LEVEL",
    PLAYER_PORTRAIT_EXPERIENCE = "PLAYER_PORTRAIT_EXPERIENCE",
    PLAYER_PORTRAIT_MONEY = "PLAYER_PORTRAIT_MONEY",
    PLAYER_PERKS = "PLAYER_PERKS",
    PLAYER_POWER = "PLAYER_POWER",
    PLAYER_VALUE = "PLAYER_VALUE",
    ENEMY_POWER = "ENEMY_POWER",
    ENEMY_VALUE = "ENEMY_VALUE",
    WIN_FIRE_TEXT = "WIN_FIRE_TEXT",
    POINTS = "POINTS",
    TOOLTIP_CARD_NAME = "TOOLTIP_CARD_NAME",
    TOOLTIP_CARD_POWER = "TOOLTIP_CARD_POWER",
    TOOLTIP_CARD_VALUE = "TOOLTIP_CARD_VALUE",
}

export enum AnimationIds {
    CARD_SELECT = "CARD_SELECT",
    CARD_UNSELECT = "CARD_UNSELECT",
    CARD_CUT = "CARD_CUT",
    CARD_SUIT_SLIDE = "CARD_SUIT_SLIDE",
    CARD_FLICKER = "CARD_FLICKER",
    CARD_DEAL = "CARD_DEAL",
    CARD_DISCARD = "CARD_DISCARD",
    CARD_RETURN_TO_DECK = "CARD_RETURN_TO_DECK",
    EDEL_CARD = "EDEL_CARD",
    SHIMMER_CARD = "SHIMMER_CARD",
}

export enum HoverEffects {
    NONE = "NONE",
    SCALE_UP = "SCALE_UP",
    CHANGE_COLOR = "CHANGE_COLOR",
    SHIFT_UP = "SHIFT_UP",
    SHIMMER = "SHIMMER",
    WOBBLE = "WOBBLE",
}

export enum MousePressEffects {
    NONE = "NONE",
    SCALE_DOWN = "SCALE_DOWN",
    DARKEN = "DARKEN",
    SHIFT_DOWN = "SHIFT_DOWN",
}
