export declare enum GameStates {
    MAIN_MENU = "MAIN_MENU",
    NEW_GAME_MENU = "NEW_GAME_MENU",
    BOARD = "BOARD",
    WIN_SCREEN = "WIN_SCREEN",
    LOSE_SCREEN = "LOSE_SCREEN",
    MAP = "MAP",
    SHOP = "SHOP",
    LEVEL_UP = "LEVEL_UP",
    PERKS = "PERKS"
}
export declare enum Suits {
    HEARTS = "HEARTS",
    BELLS = "BELLS",
    ACORNS = "ACORNS",
    LEAVES = "LEAVES"
}
export declare enum Ranks {
    KING = "KING",
    OVERLORD = "OVERLORD",
    SERGEANT = "SERGEANT",
    BANNER = "BANNER",
    THIEF = "THIEF",
    PRIEST = "PRIEST",
    SOLDIER = "SOLDIER",
    BARON = "BARON",
    JESTER = "JESTER",
    DEUCE = "DEUCE"
}
export declare enum CharacterTypes {
    PLAYER = "PLAYER",
    ENEMY = "ENEMY"
}
export declare enum MapNodeTypes {
    BATTLE = "BATTLE",
    SHOP = "SHOP"
}
export declare enum EnemyTypes {
    KOBOLD = "KOBOLD",
    NIXIE = "NIXIE",
    OGRE = "OGRE",
    TATZELWURM = "TATZELWURM"
}
export declare enum Perks {
    EXTRA_CARD = "EXTRA_CARD",
    EXTRA_DISCARD = "EXTRA_DISCARD",
    INCREASED_LOOT = "INCREASED_LOOT"
}
export declare enum AssetIds {
    BASE_CARD_TEMPLATE = "BASE_CARD_TEMPLATE",
    SUIT = "SUIT",
    RANK = "RANK",
    LETS_FIGHT_BUTTON = "LETS_FIGHT_BUTTON",
    ATTACK_BUTTON = "ATTACK_BUTTON",
    DISCARD_BUTTON = "DISCARD_BUTTON",
    DESELECT_BUTTON = "DESELECT_BUTTON",
    SORT_BUTTON = "SORT_BUTTON",
    POINT_DISPLAY = "POINT_DISPLAY",
    PLAYER_PORTRAIT_BACKGROUND = "PLAYER_PORTRAIT_BACKGROUND",
    ENEMY_PORTRAIT_BACKGROUND = "ENEMY_PORTRAIT_BACKGROUND",
    PLAYER_PORTRAIT = "PLAYER_PORTRAIT",
    ENEMY_PORTRAIT = "ENEMY_PORTRAIT",
    PLAYER_DECK = "PLAYER_DECK",
    ENEMY_DECK = "ENEMY_DECK",
    BACKGROUND = "GRASS_BACKGROUND",
    PERKS_BUTTON = "PERKS_BUTTON",
    BASIC_WIN_FIRE = "BASIC_WIN_FIRE",
    EDEL_BOARD = "EDEL_BOARD",
    EDEL_SUIT_ICON_LEFT = "EDEL_SUIT_ICON_LEFT",
    EDEL_SUIT_ICON_RIGHT = "EDEL_SUIT_ICON_RIGHT",
    TOOLTIP_BACKGROUND = "TOOLTIP_BACKGROUND",
    PLAYER_ATTACK_POWER_ICON = "PLAYER_ATTACK_POWER_ICON",
    ENEMY_ATTACK_POWER_ICON = "ENEMY_ATTACK_POWER_ICON",
    PLAYER_VALUE_ICON = "PLAYER_VALUE_ICON",
    ENEMY_VALUE_ICON = "ENEMY_VALUE_ICON",
    MONEY_ICON = "MONEY_ICON",
    TOOLTIP_POWER_ICON = "TOOLTIP_POWER_ICON",
    TOOLTIP_VALUE_ICON = "TOOLTIP_VALUE_ICON",
    EDEL_DISPLAY = "EDEL_DISPLAY",
    EDEL_ICON = "EDEL_ICON",
    POPUP_BACKGROUND = "POPUP_BACKGROUND",
    PAUSE_CONTINUE_BUTTON = "PAUSE_CONTINUE_BUTTON",
    PAUSE_SAVE_BUTTON = "PAUSE_SAVE_BUTTON",
    PAUSE_SETTINGS_BUTTON = "PAUSE_SETTINGS_BUTTON",
    PAUSE_QUIT_BUTTON = "PAUSE_QUIT_BUTTON",
    YES_BUTTON = "YES_BUTTON",
    NO_BUTTON = "NO_BUTTON"
}
export declare enum TextIds {
    LETS_FIGHT_BUTTON_CAPTION = "LETS_FIGHT_BUTTON_CAPTION",
    ATTACK_BUTTON_CAPTION = "ATTACK_BUTTON_CAPTION",
    DISCARD_BUTTON_CAPTION = "DISCARD_BUTTON_CAPTION",
    DISCARD_BUTTON_COUNTER = "DISCARD_BUTTON_COUNTER",
    DESELECT_BUTTON_CAPTION = "DESELECT_BUTTON_CAPTION",
    SORT_BUTTON_CAPTION = "SORT_BUTTON_CAPTION",
    POINTS_PLAYER = "POINTS_PLAYER",
    POINTS_ENEMY = "POINTS_ENEMY",
    EDEL_LABEL = "EDEL_LABEL",
    PLAYER_PORTRAIT_NAME = "PLAYER_PORTRAIT_NAME",
    ENEMY_PORTRAIT_NAME = "ENEMY_PORTRAIT_NAME",
    PLAYER_PORTRAIT_LEVEL = "PLAYER_PORTRAIT_LEVEL",
    ENEMY_PORTRAIT_LEVEL = "ENEMY_PORTRAIT_LEVEL",
    PLAYER_PORTRAIT_EXPERIENCE = "PLAYER_PORTRAIT_EXPERIENCE",
    PLAYER_PORTRAIT_MONEY = "PLAYER_PORTRAIT_MONEY",
    PLAYER_PERKS = "PLAYER_PERKS",
    PLAYER_POWER = "PLAYER_POWER",
    PLAYER_VALUE = "PLAYER_VALUE",
    ENEMY_POWER = "ENEMY_POWER",
    ENEMY_VALUE = "ENEMY_VALUE",
    WIN_FIRE_TEXT = "WIN_FIRE_TEXT",
    POINTS = "POINTS",
    TOOLTIP_CARD_NAME = "TOOLTIP_CARD_NAME",
    TOOLTIP_CARD_POWER = "TOOLTIP_CARD_POWER",
    TOOLTIP_CARD_VALUE = "TOOLTIP_CARD_VALUE",
    TOOLTIP_DECK_OVERVIEW_CARDS = "TOOLTIP_DECK_OVERVIEW_CARDS",
    TOOLTIP_DECK_OVERVIEW_DISCARDS = "TOOLTIP_DECK_OVERVIEW_DISCARDS",
    PAUSE_CONTINUE_BUTTON_CAPTION = "PAUSE_CONTINUE_BUTTON_CAPTION",
    PAUSE_SAVE_BUTTON_CAPTION = "PAUSE_SAVE_BUTTON_CAPTION",
    PAUSE_SETTINGS_BUTTON_CAPTION = "PAUSE_SETTINGS_BUTTON_CAPTION",
    PAUSE_QUIT_BUTTON_CAPTION = "PAUSE_QUIT_BUTTON_CAPTION",
    POPUP_TITLE = "POPUP_TITLE",
    YES_BUTTON_CAPTION = "YES_BUTTON_CAPTION",
    NO_BUTTON_CAPTION = "NO_BUTTON_CAPTION",
    PROMPT_SECONDARY_MESSAGE = "PROMPT_SECONDARY_MESSAGE"
}
export declare enum PopupIds {
    DECK_CONTENTS = "DECK_CONTENTS",
    PAUSE_MENU = "PAUSE_MENU",
    QUIT_PROMPT = "QUIT_PROMPT"
}
export declare enum HoverEffects {
    NONE = "NONE",
    SCALE_UP = "SCALE_UP",
    CHANGE_COLOR = "CHANGE_COLOR",
    SHIFT_UP = "SHIFT_UP",
    SHIMMER = "SHIMMER",
    WOBBLE = "WOBBLE"
}
export declare enum MousePressEffects {
    NONE = "NONE",
    SCALE_DOWN = "SCALE_DOWN",
    DARKEN = "DARKEN",
    SHIFT_DOWN = "SHIFT_DOWN"
}
