export enum GameStates {
    MAIN_MENU = "MAIN_MENU",
    NEW_GAME_MENU = "NEW_GAME_MENU",
    BOARD = "BOARD",
    PAUSE_MENU = "PAUSE_MENU",
    WIN_SCREEN = "WIN_SCREEN",
    LOSE_SCREEN = "LOSE_SCREEN",
    MAP = "MAP",
    SHOP = "SHOP",
    LEVEL_UP = "LEVEL_UP",
    PERKS = "PERKS",
}
export enum Suits {
    HEARTS = "HEARTS",
    BELLS = "BELLS",
    ACORNS = "ACORNS",
    LEAVES = "LEAVES",
}

export enum Ranks {
    KING = "KING",
    OVERLORD = "OVERLORD",
    SERGEANT = "SERGEANT",
    BANNER = "BANNER",
    THIEF = "THIEF",
    PRIEST = "PRIEST",
    SOLDIER = "SOLDIER",
    BARON = "BARON",
    JESTER = "JESTER",
    DEUCE = "DEUCE"
}

export enum TrumpRanks {
    CHOSEN = "CHOSEN",
    DEVIL = "DEVIL",
    POPE = "POPE",
    EMPEROR = "EMPEROR",
    BARD = "BARD",
    DUKE = "DUKE",
    KNIGHT = "KNIGHT",
}

export enum CharacterTypes {
    PLAYER = "PLAYER",
    ENEMY = "ENEMY",
}

export enum MapNodeTypes {
    BATTLE = "BATTLE",
    SHOP = "SHOP",
    // Belsnickel
    // Bergmonch
    // Feldgeister
}

export enum EnemyTypes {
    KOBOLD = "KOBOLD",
    NIXIE = "NIXIE",
    OGRE = "OGRE",
    TATZELWURM = "TATZELWURM",
    // Alp
    // Lindworm
    // Night raven

}

export enum Perks {
    EXTRA_CARD = "EXTRA_CARD",
    EXTRA_DISCARD = "EXTRA_DISCARD",
    INCREASED_LOOT = "INCREASED_LOOT",
}

export enum AssetIds {
    BASE_CARD_TEMPLATE = "BASE_CARD_TEMPLATE",
    SUIT = "SUIT",
    LETS_FIGHT_BUTTON = "LETS_FIGHT_BUTTON",
    RANK = "RANK",
    ATTACK_BUTTON = "ATTACK_BUTTON",
    DISCARD_BUTTON = "DISCARD_BUTTON",
    DESELECT_BUTTON = "DESELECT_BUTTON",
    POINT_DISPLAY = "POINT_DISPLAY",
    PLAYER_PORTRAIT = "PLAYER_PORTRAIT", 
    ENEMY_PORTRAIT = "ENEMY_PORTRAIT",
    PLAYER_DECK = "PLAYER_DECK",
    ENEMY_DECK = "ENEMY_DECK",
    GRASS_BACKGROUND = "GRASS_BACKGROUND",
}

export enum FontIds {
    ATTACK_BUTTON_CAPTION = "ATTACK_BUTTON_CAPTION",
    DISCARD_BUTTON_CAPTION = "DISCARD_BUTTON_CAPTION",
    DESELECT_BUTTON_CAPTION = "DESELECT_BUTTON_CAPTION",
    POINTS_PLAYER = "POINTS_PLAYER",
    POINTS_ENEMY = "POINTS_ENEMY",
}

export enum AnimationIds {
    CARD_BASE_SELECT = "CARD_BASE_SELECT",
    CARD_BASE_UNSELECT = "CARD_BASE_UNSELECT",
    CARD_SUIT_NORMAL_SELECT = "CARD_SUIT_NORMAL_SELECT",
    CARD_SUIT_NORMAL_UNSELECT = "CARD_SUIT_NORMAL_UNSELECT",
    CARD_SUIT_FLIPPED_SELECT = "CARD_SUIT_FLIPPED_SELECT",
    CARD_SUIT_FLIPPED_UNSELECT = "CARD_SUIT_FLIPPED_UNSELECT",
    CARD_RANK_SELECT = "CARD_RANK_NORMAL_SELECT",
    CARD_RANK_UNSELECT = "CARD_RANK_NORMAL_UNSELECT",
}

export enum Biomes {
    GRASS = "GRASS",
}
