/** @noSelfInFile */
import { GameStates } from "./Enums";
import MainMenu from "Screens/MainMenu";
import NewGameMenu from "Screens/NewGameMenu";
import PauseMenu from "Screens/PauseMenu";
import Board from "Screens/Board";
import WinScreen from "Screens/WinScreen";
import LoseScreen from "Screens/LoseScreen";
import Settings from "Settings";
import Character from "Character";
import Player from "Player";
import Map from "Screens/Map/Map";
import Enemy from "Enemies/Enemy";
import Shop from "Screens/Shop";
import LevelUpScreen from "Screens/LevelUpScreen";
import PerkScreen from "Screens/PerkScreen";
export default class GameManager {
    gameState: GameStates;
    player: Player;
    settings: Settings;
    mainMenu?: MainMenu;
    newGameMenu?: NewGameMenu;
    pauseMenu?: PauseMenu;
    board?: Board;
    winScreen?: WinScreen;
    loseScreen?: LoseScreen;
    map: Map;
    shop?: Shop;
    levelUpScreen?: LevelUpScreen;
    perkScreen?: PerkScreen;
    constructor();
    getCharacter(characterType: string): Character | undefined;
    switchBasedOnGameState(): void;
    switchToMainMenu(): void;
    switchToNewGameMenu(): void;
    switchToPauseMenu(): void;
    switchToBoard(enemy?: Enemy): void;
    switchToWinScreen(): void;
    switchToLoseScreen(): void;
    switchToMap(): void;
    switchToShop(): void;
    switchToLevelUpScreen(): void;
    switchToPerkScreen(): void;
}
