/** @noSelfInFile */
import AnimationManager from "Assets/Animations/AnimationManager";
import AssetManager from "Assets/AssetManager";
import MusicPlayer from "Assets/Music/MusicPlayer";
import Biome from "Biomes/Biome";
import Character from "Character";
import Enemy from "Enemies/Enemy";
import Player from "Player";
import BackgroundManager from "Screens/BackgroundManager";
import Board from "Screens/Board";
import LevelUpScreen from "Screens/LevelUpScreen";
import LoseScreen from "Screens/LoseScreen";
import MainMenu from "Screens/MainMenu";
import Map from "Screens/Map/Map";
import NewGameMenu from "Screens/NewGameMenu";
import PauseMenu from "Screens/PauseMenu";
import PerkScreen from "Screens/PerkScreen";
import PopupManager from "Screens/Popup/PopupManager";
import Shop from "Screens/Shop";
import WinScreen from "Screens/WinScreen";
import Settings from "Settings";
import ShaderManager from "Shaders/ShaderManager";
import { GameStates } from "./Enums";
export default class GameManager {
    gameState: GameStates;
    player: Player;
    settings: Settings;
    mainMenu?: MainMenu;
    newGameMenu?: NewGameMenu;
    pauseMenu: PauseMenu;
    board?: Board;
    winScreen?: WinScreen;
    loseScreen?: LoseScreen;
    map: Map;
    shop?: Shop;
    levelUpScreen?: LevelUpScreen;
    perkScreen: PerkScreen;
    assetManager: AssetManager;
    animationManager: AnimationManager;
    musicPlayer: MusicPlayer;
    biome: Biome;
    backgroundManager: BackgroundManager;
    shaderManager: ShaderManager;
    popupManager: PopupManager;
    devMode: boolean;
    constructor();
    getCharacter(characterType: string): Character | undefined;
    switchBasedOnGameState(gameState?: GameStates, enemy?: Enemy | undefined): void;
    private switchToMainMenu;
    private switchToNewGameMenu;
    private switchToBoard;
    private switchToWinScreen;
    private switchToLoseScreen;
    private switchToMap;
    private switchToShop;
    private switchToLevelUpScreen;
}
