import { Source } from "love.audio";
import { Image } from "love.graphics";
import FontWithPosition from "./FontWithPosition";
import { HoverEffects, MousePressEffects } from "Enums";
import QuadWithPosition from "./QuadWithPosition";
import GameManager from "GameManager";
export type AssetCallback = (asset: Asset) => void;
export interface ConstructionOptions {
    readonly onClick?: () => void;
    readonly onHover?: AssetCallback;
    readonly onUnhover?: AssetCallback;
    readonly orientation?: number;
    readonly scaleX?: number;
    readonly scaleY?: number;
    readonly offsetX?: number;
    readonly offsetY?: number;
    readonly quads?: QuadWithPosition[];
    readonly isDisabled?: boolean;
    readonly useDisabledAnimation?: boolean;
    readonly clickSound?: Source;
    readonly associatedTexts?: FontWithPosition[];
    readonly hoverEffect?: HoverEffects[];
    readonly mousePressEffect?: MousePressEffects[];
}
export default class Asset {
    gameManager: GameManager;
    id: string;
    image: Image;
    x: number;
    y: number;
    width: number;
    height: number;
    onClick?: () => void;
    onHover?: AssetCallback;
    onUnhover?: AssetCallback;
    orientation: number;
    scaleX: number;
    scaleY: number;
    offsetX: number;
    offsetY: number;
    quads: QuadWithPosition[];
    isDisabled: boolean;
    useDisabledAnimation: boolean;
    isHovered: boolean;
    isPressed: boolean;
    color: [number, number, number, number];
    clickSound?: Source;
    associatedTexts?: FontWithPosition[];
    hoverEffect: HoverEffects[];
    mousePressEffect: MousePressEffects[];
    isHidden: boolean;
    constructor(gameManager: GameManager, id: string, image: Image, x: number, y: number, width: number, height: number, constructionOptions?: ConstructionOptions);
    drawAsset(): void;
    updatePosition(x: number, y: number): void;
    setHovered(hovered: boolean): void;
    private handleHoverEffects;
    setMousePressed(pressed: boolean): void;
    private handleMousePressEffects;
    setDisabled(disabled: boolean): void;
    setColor(): void;
    getWidth(): number;
    getHeight(): number;
    private scaleDown;
    private scaleUp;
    private shiftDown;
    private shiftUp;
    private shimmer;
    private wobble;
}
