/** @noSelfInFile */
import { CharacterTypes, Suits } from "../Enums";
import Dealer from "../Dealer";
import Enemy, { EnemyData } from "Enemies/Enemy";
import type GameManager from "../GameManager";
import CardAssets from "Assets/CardAssets";
import { Image } from "love.graphics";
interface BoardData {
    discardUsed: number;
    playerPoints: number;
    enemyPoints: number;
    enemy: EnemyData;
    edelSuit: Suits;
    playerPower: number;
    playerValue: number;
    enemyPower: number;
    enemyValue: number;
    showingInitialView: boolean;
}
export default class Board {
    gameManager: GameManager;
    discardUsed: number;
    enemy: Enemy;
    dealer: Dealer;
    playerPoints: number;
    enemyPoints: number;
    edelSuit: Suits;
    playerPower: number;
    playerValue: number;
    enemyPower: number;
    enemyValue: number;
    showingEdelView: boolean;
    cardAssets: CardAssets;
    letsFightButton: Image;
    attackButton: Image;
    discardButton: Image;
    deselectButton: Image;
    pointBoard: Image;
    edelBoard: Image;
    portraitBackground: Image;
    portrait: Image;
    baseDeck: Image;
    perksButton: Image;
    markIcon: Image;
    attackPowerIcon: Image;
    valueIcon: Image;
    portraitPosition: number | undefined;
    winFireSound: import("love.audio").Source;
    constructor(gameManager: GameManager, enemy?: Enemy);
    load(data: BoardData): void;
    save(): BoardData;
    getPlayerPoints(): number;
    getEnemyPoints(): number;
    handleStartFight(): void;
    buildFightAssets(): void;
    private hideEdelBoard;
    handleAttack(): void;
    private addPlayerPoints;
    private addEnemyPoints;
    handleDiscard(): void;
    getRemainingDiscards(): number;
    getWinner(): CharacterTypes;
    endFight(): void;
    private clearStats;
    private clearPlayerStats;
    private clearEnemyStats;
    addPlayerPower(power: number): void;
    addPlayerValue(value: number): void;
    addEnemyPower(power: number): void;
    addEnemyValue(value: number): void;
    buildAssets(): void;
    private buildCardAssets;
    private buildLetsFightButton;
    private buildPrimaryButtons;
    private buildAttackButton;
    private buildDiscardButton;
    private buildDeselectButton;
    updatePrimaryButtonStates(): void;
    private buildPointBoard;
    private buildPowerAndValues;
    private buildPlayerPortrait;
    private buildEnemyPortrait;
    private buildPortrait;
    private buildPlayerDeck;
    private buildEnemyDeck;
    private buildEdelBoard;
    private buildBackground;
    private playWinFireSound;
    private buildWinFire;
    private removeWinFire;
    private getWinFireSprite;
    getPortraitPosition(characterType: CharacterTypes): number;
}
export {};
