/** @noSelfInFile */
import CardAssets from "Assets/CardAssets";
import Card from "Cards/Card";
import Enemy, { EnemyData } from "Enemies/Enemy";
import Dealer from "../Dealer";
import { CharacterTypes } from "../Enums";
import type GameManager from "../GameManager";
interface BoardData {
    discardUsed: number;
    playerPoints: number;
    enemyPoints: number;
    enemy: EnemyData;
    edelCard?: Card;
    playerPower: number;
    playerValue: number;
    enemyPower: number;
    enemyValue: number;
    showingInitialView: boolean;
}
export default class Board {
    gameManager: GameManager;
    discardUsed: number;
    enemy: Enemy;
    dealer: Dealer;
    playerPoints: number;
    enemyPoints: number;
    edelCard?: Card;
    playerPower: number;
    playerValue: number;
    enemyPower: number;
    enemyValue: number;
    showingEdelView: boolean;
    cardAssets: CardAssets;
    portraitPosition: number | undefined;
    winFireSound: import("love.audio").Source;
    constructor(gameManager: GameManager, enemy?: Enemy);
    load(data: BoardData): void;
    save(): BoardData;
    getPlayerPoints(): number;
    getEnemyPoints(): number;
    handleStartFight(): void;
    private hideEdelBoard;
    handleAttack(): void;
    getSlainCards(characterType: CharacterTypes): Card[];
    startCutAnimation(card: Card, winner: CharacterTypes, loser: CharacterTypes): void;
    startFlickerAnimation(card: Card, winner: CharacterTypes, loser: CharacterTypes): void;
    wrapUpAttack(winner: CharacterTypes, loser: CharacterTypes): void;
    private hideSlainCards;
    private addPlayerPoints;
    getAllCardsInPlay(): Card[];
    private addPoints;
    private addEnemyPoints;
    displayEdel(): void;
    displayFight(): void;
    handleDiscard(): void;
    updateDiscardCounter(remainingNumberOfDiscards: number): void;
    getRemainingDiscards(): number;
    getWinner(): CharacterTypes;
    endFight(): void;
    clearStats(): void;
    clearPlayerStats(): void;
    clearEnemyStats(): void;
    addPlayerPower(power: number): void;
    addPlayerValue(value: number): void;
    addEnemyPower(power: number): void;
    addEnemyValue(value: number): void;
    start(): void;
    private buildLetsFightButton;
    private buildPrimaryButtons;
    private buildAttackButton;
    private buildDiscardButton;
    private buildDeselectButton;
    updatePrimaryButtonStates(): void;
    enableAttackButton(): void;
    enableDiscardButton(): void;
    enableDeselectButton(): void;
    disableAttackButton(): void;
    disableDiscardButton(): void;
    disableDeselectButton(): void;
    private buildPointBoard;
    private buildPowerAndValues;
    private buildPlayerPortrait;
    private getPortraitHeight;
    private getPortraitWidth;
    private buildEnemyPortrait;
    private buildPortrait;
    buildDeck(characterType: CharacterTypes): void;
    private buildEdelBoard;
    private playWinFireSound;
    private buildWinFire;
    private removeWinFire;
    private getWinFireSprite;
    getPortraitPosition(characterType: CharacterTypes): number;
    tallyEnemyPowerAndValue(): void;
}
export {};
